# Generated by Django 6.0.6 on 2026-06-29 20:48

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFilter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief context for the filter.', null=True)),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Visible to all authenticated users.')),
                ('is_global', models.BooleanField(db_index=True, default=False, help_text='System-wide defaults (Staff only).')),
                ('criteria', models.JSONField(default=dict, help_text='Key-value pairs for filtering.')),
                ('selected_fields', models.JSONField(default=list, help_text='List of string fields to include in the CSV.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=80, null=True, validators=[django.core.validators.MaxLengthValidator(80)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('applied_criteria', models.JSONField(default=dict)),
                ('selected_fields', models.JSONField(default=list)),
                ('file_path', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/Astraea-Webserver/backend/protected_storage'), upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportfilter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='reportfilter',
            index=models.Index(fields=['is_public', 'is_global'], name='reports_rep_is_publ_171a99_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfilter',
            index=models.Index(fields=['user'], name='reports_rep_user_id_347030_idx'),
        ),
    ]
