# Generated by Django 6.0.6 on 2026-06-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfilter',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
