# Generated by Django 6.0.3 on 2026-04-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('notifications_sent', models.BooleanField(db_index=True, default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='For delayed notifications', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('successful_services', models.ManyToManyField(blank=True, related_name='received_notifications', to='configuration.notificationservice')),
            ],
            options={
                'verbose_name_plural': 'Pending Notifications',
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_376ef6_idx')],
            },
        ),
    ]
