# Generated by Django 6.0.4 on 2026-05-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('servers', '0004_server_enable_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingnotification',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='servers.server'),
        ),
    ]
