# Generated by Django 6.0.6 on 2026-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pendingnotification_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingnotification',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
