# Generated by Django 6.0 on 2026-03-30 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="e.g., 'Production Linux Cluster'", max_length=100)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AstraeaAgentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Agent Agent Info',
            },
        ),
        migrations.CreateModel(
            name='NotificationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'Ops Discord Channel'", max_length=100)),
                ('type', models.CharField(choices=[('discord', 'Discord Webhook'), ('smtp', 'SMTP Email'), ('slack', 'Slack Webhook')], default='discord', max_length=20)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('recipients', models.TextField(blank=True, help_text='Comma-separated emails', null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Services',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=True)),
                ('partial', models.BooleanField(default=True)),
                ('out_of_date', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patching_enabled', models.BooleanField(default=True)),
                ('skip_email_validation', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentInstallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A friendly name for this configuration', max_length=100)),
                ('uid', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('exe_logic', models.CharField(choices=[('standard', 'Standard (Every Execution)'), ('week1and3', 'Patching Week 1 & 3'), ('week2and4', 'Patching Week 2 & 4')], default='default', max_length=20)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('cron', models.CharField(default='0 0 * * *', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_configs', to='configuration.apikey')),
            ],
            options={
                'verbose_name_plural': 'Agent Install Configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
