# Generated by Django 6.0.4 on 2026-05-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinstallconfig',
            name='exe_logic',
            field=models.CharField(choices=[('standard', 'Standard (Every Execution)'), ('week1and3', 'Patching Week 1 & 3'), ('week2and4', 'Patching Week 2 & 4'), ('week1', 'Patching Week 1'), ('week2', 'Patching Week 2'), ('week3', 'Patching Week 3'), ('week4', 'Patching Week 4')], default='standard', max_length=20),
        ),
    ]
