# Generated by Django 6.0.4 on 2026-06-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_agentinstallconfig_exe_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstallconfig',
            name='disable_autoremove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentinstallconfig',
            name='enable_apt_release_info_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentinstallconfig',
            name='max_allowed_uptime',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='agentinstallconfig',
            name='reboot_after_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentinstallconfig',
            name='reboot_on_success',
            field=models.BooleanField(default=False),
        ),
    ]
