# Generated by Django 6.0.6 on 2026-06-25 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_agentinstallconfig_disable_autoremove_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('api_url', models.URLField(help_text='e.g., http://zabbix.example.com/')),
                ('api_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ZabbixMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('host_id', models.CharField(max_length=50)),
                ('maintenance_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zabbix_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.zabbixconfiguration')),
            ],
            options={
                'verbose_name': 'Zabbix Maintenance Tracker',
            },
        ),
    ]
