# Generated by Django 6.0.6 on 2026-06-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_zabbixconfiguration_zabbixmaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabbixconfiguration',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zabbixconfiguration',
            name='api_url',
            field=models.URLField(blank=True, help_text='e.g., http://zabbix.example.com/', null=True),
        ),
    ]
