# Generated by Django 6.0.6 on 2026-06-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_zabbixconfiguration_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationservice',
            name='email_all_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationservice',
            name='main_email_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated emails', null=True),
        ),
    ]
