# Generated by Django 6.0.6 on 2026-07-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_notificationservice_email_all_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstallconfig',
            name='base_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
