# Generated by Django 6.0.6 on 2026-07-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_agentinstallconfig_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='on_server_add',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='on_server_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='on_server_modify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='site_outdated',
            field=models.BooleanField(default=True),
        ),
    ]
