# Generated by Django 6.0.6 on 2026-07-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUpdateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('latest_version_on_github', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Agent Update Check',
            },
        ),
        migrations.CreateModel(
            name='UpdateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('latest_version_on_github', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Update Check',
            },
        ),
    ]
