# Generated by Django 6.0 on 2026-03-23 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Production Linux Cluster'", max_length=100)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Failure'), ('failed', 'Failed')], default='success', max_length=10)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('total_updated', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True)),
                ('os_version', models.CharField(blank=True, max_length=100, null=True)),
                ('uptime', models.CharField(blank=True, max_length=100, null=True)),
                ('last_reboot', models.DateTimeField(blank=True, null=True)),
                ('last_patch_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('patch_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('enable_patching', models.BooleanField(db_index=True, default=True)),
                ('env', models.CharField(blank=True, max_length=100, null=True)),
                ('total_packages_updated', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PackageUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_version', models.CharField(blank=True, max_length=100, null=True)),
                ('new_version', models.CharField(max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='servers.package')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_details', to='servers.patchsession')),
            ],
        ),
        migrations.AddField(
            model_name='patchsession',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patch_sessions', to='servers.server'),
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=17, null=True)),
                ('interface_name', models.CharField(blank=True, max_length=50, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='servers.server')),
            ],
            options={
                'verbose_name': 'Network Interface',
            },
        ),
        migrations.AddIndex(
            model_name='patchsession',
            index=models.Index(fields=['server', '-timestamp'], name='servers_pat_server__bd20cd_idx'),
        ),
    ]
