# Generated by Django 6.0 on 2026-03-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
