# Generated by Django 6.0.4 on 2026-05-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_delete_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
