# Generated by Django 6.0.4 on 2026-05-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='enable_notifications',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
