# Generated by Django 6.0.4 on 2026-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_server_enable_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchsession',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
