# Generated by Django 6.0.4 on 2026-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_patchsession_duration_server_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='disable_autoremove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='enable_apt_release_info_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='max_allowed_uptime',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='server',
            name='reboot_after_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='reboot_on_success',
            field=models.BooleanField(default=False),
        ),
    ]
