# Generated by Django 6.0.6 on 2026-06-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_server_disable_autoremove_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='enable_zabbix',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
