# Generated by Django 6.0.6 on 2026-06-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_server_enable_zabbix'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchsession',
            name='was_rebooted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='was_rebooted',
            field=models.BooleanField(default=False),
        ),
    ]
