# Generated by Django 6.0.6 on 2026-06-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_patchsession_was_rebooted_server_was_rebooted'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchsession',
            name='uptime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
