# Generated by Django 6.0.6 on 2026-07-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_patchsession_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
