#!/bin/bash
# Astraea Agent Auto-Installer
set -e

API_KEY="{{ API_KEY }}"
BASE_URL="{{ BASE_URL }}"
ASTRAEA_UID="{{ UID }}"
EXE_LOGIC="{{ EXE_LOGIC }}"
ENVIRONMENT="{{ ENVIRONMENT }}"
CRON_SCHEDULE="{{ CRON }}"
PATCHING_SCHEDULE="{{ PATCHING_SCHEDULE }}"
DISABLE_AUTOREMOVE="{{ DISABLE_AUTOREMOVE }}"
ENABLE_APT_ALLOW_RELEASE_INFO_CHANGE="{{ ENABLE_APT_ALLOW_RELEASE_INFO_CHANGE }}"
REBOOT_ON_SUCCESS="{{ REBOOT_ON_SUCCESS }}"
REBOOT_AFTER_UPDATES="{{ REBOOT_AFTER_UPDATES }}"
MAX_ALLOWED_UPTIME_DAYS="{{ MAX_ALLOWED_UPTIME_DAYS }}"

INSTALL_DIR="/opt/Astraea-Agent"
CRON_FILE="/etc/cron.d/astraea-agent-schedule"

if [[ $EUID -ne 0 ]]; then 
   echo "Please run as root (sudo)" 
   exit 1
fi

echo "--- Fetching Astraea Agent Package ---"
mkdir -p $INSTALL_DIR
if ! curl -f -sSL -H "X-Api-Key: $API_KEY" -o astraea_agent.tar.gz "$BASE_URL/api/config/agent_file/"; then
    echo "❌ Failed to download the Astraea Agent. Check your API_KEY, BASE_URL, or server logs."
    exit 1
fi
tar -xzf astraea_agent.tar.gz -C $INSTALL_DIR --strip-components=1
rm astraea_agent.tar.gz
cd $INSTALL_DIR


if [ "$EXE_LOGIC" != "standard" ]; then
    echo "--- Downloading Logic Script: $EXE_LOGIC ---"
    if ! curl -f -sSL -o "patching-$EXE_LOGIC.sh" "$BASE_URL/api/config/install_script/$ASTRAEA_UID/?file=logic_script"; then
        echo "❌ Failed to download the Patching Execution Logic. Check your BASE_URL, or server logs."
        exit 1
    fi
    chmod +x "patching-$EXE_LOGIC.sh"
fi

if [ -f ".env_example" ]; then
    if [ ! -f ".env" ]; then
        cp ".env_example" ".env"
    else
        echo ".env already exists, skipping copy."
    fi
else
    echo "Warning: env_example not found."
fi

sed -i "s|^API_KEY=.*|API_KEY=$API_KEY|" .env
sed -i "s|^ENV=.*|ENV=$ENVIRONMENT|" .env
PATCH_SCHEDULE_ESCAPED=$(echo "{{ PATCHING_SCHEDULE|safe }}" | sed 's/&/\\&/g')
sed -i "s|^PATCH_SCHEDULE=.*|PATCH_SCHEDULE=$PATCH_SCHEDULE_ESCAPED|" .env
sed -i "s|^BASE_URL=.*|BASE_URL=$BASE_URL|" .env
sed -i "s|^DISABLE_AUTOREMOVE=.*|DISABLE_AUTOREMOVE=$DISABLE_AUTOREMOVE|" .env
sed -i "s|^ENABLE_APT_ALLOW_RELEASE_INFO_CHANGE=.*|ENABLE_APT_ALLOW_RELEASE_INFO_CHANGE=$ENABLE_APT_ALLOW_RELEASE_INFO_CHANGE|" .env
sed -i "s|^REBOOT_ON_SUCCESS=.*|REBOOT_ON_SUCCESS=$REBOOT_ON_SUCCESS|" .env
sed -i "s|^REBOOT_AFTER_UPDATES=.*|REBOOT_AFTER_UPDATES=$REBOOT_AFTER_UPDATES|" .env
sed -i "s|^MAX_ALLOWED_UPTIME_DAYS=.*|MAX_ALLOWED_UPTIME_DAYS=$MAX_ALLOWED_UPTIME_DAYS|" .env

echo "--- Configuration Applied ---"

if [ "$EXE_LOGIC" == "week1and3" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week1and3.sh"
elif [ "$EXE_LOGIC" == "week2and4" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week2and4.sh"
elif [ "$EXE_LOGIC" == "week1" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week1.sh"
elif [ "$EXE_LOGIC" == "week2" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week2.sh"
elif [ "$EXE_LOGIC" == "week3" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week3.sh"
elif [ "$EXE_LOGIC" == "week4" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week4.sh"
else
    EXEC_CMD="/usr/bin/python3 $INSTALL_DIR/core/initialize.py"
fi

if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    echo "❌ Cannot detect OS. Please install dependencies manually."
    exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo "--- Installing base Python3 ---"
    case $OS in
        ubuntu|debian)
            apt update && apt install -y python3 ;;
        fedora|centos|rhel)
            dnf install -y python3 ;;
    esac
fi

PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')

IS_MODERN=$(python3 -c "import sys; print(1 if sys.version_info >= (3, 10) else 0)")

if [ "$IS_MODERN" -ne 1 ]; then
    echo "❌ Astraea Agent requires Python 3.10 or higher. Found version: $PYTHON_VERSION"
    exit 1
fi

case $OS in
    ubuntu|debian)
        apt update
        apt install -y "python${PYTHON_VERSION}-venv"
        ;;
    
    fedora|centos|rhel)
        if [[ "$OS" != "fedora" ]]; then
            dnf install -y epel-release
        fi
        dnf install -y python3 python3-devel
        ;;

    *)
        echo "❌ Unsupported OS: $OS."
        exit 1
    ;;
esac

echo "--- Configuring System Cron: $CRON_FILE ---"

cat <<EOF > $CRON_FILE
# Astraea Agent Patching Schedule
# Automatically generated by installer
$CRON_SCHEDULE root cd $INSTALL_DIR && $EXEC_CMD >> /var/log/astraea-patch-cron.log 2>&1
EOF

chmod 644 $CRON_FILE

(crontab -l 2>/dev/null | grep -v "$INSTALL_DIR") | crontab - || true

echo "--- Installation Complete: Logic [$EXE_LOGIC] applied ---"