#!/bin/bash
# Astraea Agent Auto-Installer
set -e

# 1. Variables injected by Django Template
API_KEY="{{ API_KEY }}"
BASE_URL="{{ BASE_URL }}"
ASTRAEA_UID="{{ UID }}"
EXE_LOGIC="{{ EXE_LOGIC }}"
ENVIRONMENT="{{ ENVIRONMENT }}"
CRON_SCHEDULE="{{ CRON }}"
PATCHING_SCHEDULE="{{ PATCHING_SCHEDULE }}"

INSTALL_DIR="/opt/Astraea-Agent"
CRON_FILE="/etc/cron.d/astraea-agent-schedule"

if [[ $EUID -ne 0 ]]; then 
   echo "Please run as root (sudo)" 
   exit 1
fi

echo "--- Fetching Astraea Agent Package ---"
mkdir -p $INSTALL_DIR
# Use internal API key to download the core tarball
curl -sSL -H "X-Api-Key: $API_KEY" -o astraea_agent.tar.gz "$BASE_URL/api/config/agent_file/"
tar -xzf astraea_agent.tar.gz -C $INSTALL_DIR --strip-components=1
cd $INSTALL_DIR

# 2. FAILSAFE: Download Logic-Specific Script
# If the logic isn't standard, we download the patching-week script from the server
if [ "$EXE_LOGIC" != "standard" ]; then
    echo "--- Downloading Logic Script: $EXE_LOGIC ---"
    # We call back to the view asking for the 'logic_script'
    curl -sSL -o "patching-$EXE_LOGIC.sh" \
         "$BASE_URL/api/config/install_script/$ASTRAEA_UID/?file=logic_script"
    chmod +x "patching-$EXE_LOGIC.sh"
fi

# 3. Configures '.env'
if [ -f ".env_example" ]; then
    if [ ! -f ".env" ]; then
        cp ".env_example" ".env"
    else
        echo ".env already exists, skipping copy."
    fi
else
    echo "Warning: env_example not found."
fi

# 4. Edit .env
sed -i "s|^API_KEY=.*|API_KEY=$API_KEY|" .env
sed -i "s|^ENV=.*|ENV=$ENVIRONMENT|" .env
PATCH_SCHEDULE_ESCAPED=$(echo "{{ PATCHING_SCHEDULE|safe }}" | sed 's/&/\\&/g')
sed -i "s|^PATCH_SCHEDULE=.*|PATCH_SCHEDULE=$PATCH_SCHEDULE_ESCAPED|" .env
sed -i "s|^BASE_URL=.*|BASE_URL=$BASE_URL|" .env

echo "--- Configuration Applied ---"

# 5. Determine Execution Path
if [ "$EXE_LOGIC" == "week1and3" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week1and3.sh"
elif [ "$EXE_LOGIC" == "week2and4" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week2and4.sh"
elif [ "$EXE_LOGIC" == "week1" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week1.sh"
elif [ "$EXE_LOGIC" == "week2" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week2.sh"
elif [ "$EXE_LOGIC" == "week3" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week3.sh"
elif [ "$EXE_LOGIC" == "week4" ]; then
    EXEC_CMD="/bin/bash $INSTALL_DIR/patching-week4.sh"
else
    EXEC_CMD="/usr/bin/python3 $INSTALL_DIR/core/initialize.py"
fi

# 6 Install Python3.10-venv
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    echo "❌ Cannot detect OS. Please install dependencies manually."
    exit 1
fi

case $OS in
    ubuntu|debian)
        sudo apt update
        sudo apt install -y python3.10-venv
        ;;
    
    fedora|centos|rhel)
        if [[ "$OS" != "fedora" ]]; then
            sudo dnf install -y epel-release
        fi
        sudo dnf install -y python3 python3-devel
        ;;

    *)
        echo "❌ Unsupported OS: $OS."
        exit 1
    ;;
esac

# 7. Cron Setup (/etc/cron.d/ style)
echo "--- Configuring System Cron: $CRON_FILE ---"

cat <<EOF > $CRON_FILE
# Astraea Agent Patching Schedule
# Automatically generated by installer
$CRON_SCHEDULE root cd $INSTALL_DIR && $EXEC_CMD >> /var/log/astraea-patch-cron.log 2>&1
EOF

chmod 644 $CRON_FILE

# Remove any old entry from the user's personal crontab to avoid duplicates
(crontab -l 2>/dev/null | grep -v "$INSTALL_DIR") | crontab - || true

echo "--- Installation Complete: Logic [$EXE_LOGIC] applied ---"